### ISSUE TITLE
[Discussion] kernel uapi.h for 12

### ISSUE THREAD

**Issue by unicornx** [riscv-android-src/platform-bionic#9]
When I compared riscv64-android-12.0.0_dev with android-12.0.0_r2 for the `bionic/libc/kernel/uapi`, I find the difference is very large, such as asm-x86, asm-arm also have files different.

What kernel version does current riscv64-android-12.0.0_dev use?

Following the "bionic/libc/kernel/README.md", I find the android-12.0.0_r2 should uses v5.12 kernel headers.

My steps are described as below:

enter repo `external/kernel-headers/`, checkout android-12.0.0_r2

run `git log` then we can know this 12.0.0_r2 tag corresponds to kernel 5.12

```
$ git log
commit 607047d7c127efdedf74933bc07361e839114054 (HEAD, tag: android-vts-12.0_r1, tag: android-s-beta-2, tag: android-cts-12.0_r1, tag: android-12.0.0_r3, tag: android-12.0.0_r2, tag: android-12.0.0_r1, tag: m/android-12.0.0_r3, aosp/android12-tests-release, aosp/android12-s1-release, aosp/android12-release)
Merge: 74cb5e0 41e1fe5
Author: android-build-team Robot <android-build-team-robot@google.com>
Date:   Wed May 5 01:03:34 2021 +0000

    Snap for 7336869 from 41e1fe51504e14d2ac81d90f8900478a55d897d8 to sc-release
    
    Change-Id: I60ee4604bb1141f6de28aae7df81dbf93da1ad13

commit 41e1fe51504e14d2ac81d90f8900478a55d897d8 (aosp/android12-dev)
Merge: 1a37206 f684b98
Author: Christopher Ferris <cferris@google.com>
Date:   Tue May 4 19:01:51 2021 +0000

    Merge "Update to v5.12 kernel headers." am: fad4f8fd49 am: 0ac04c2374 am: f684b983c7
    
    Original change: https://android-review.googlesource.com/c/platform/external/kernel-headers/+/1694337
    
    Change-Id: I1fb5ec883b2d8adc2a430f22a415ad678513e731

commit f684b983c735ccc4e5d17f529bec50450178859d
Merge: 9335451 0ac04c2
Author: Christopher Ferris <cferris@google.com>
Date:   Tue May 4 18:38:16 2021 +0000

    Merge "Update to v5.12 kernel headers." am: fad4f8fd49 am: 0ac04c2374
    
    Original change: https://android-review.googlesource.com/c/platform/external/kernel-headers/+/1694337

......
```

Download the Android mainline kernel source code:
```
  $ mkdir kernel_src
  $ cd kernel_src
  $ git clone https://android.googlesource.com/kernel/common/ -b android-mainline
```

check out a particular tag， this is 5.12
```
$ cd common
$ git checkout tags/android-mainline-5.12
```

Before running the command to import the headers, make sure that you have done a lunch TARGET.

After running lunch, run this command to import the headers into the Android
source tree if there is a kernel source tree already checked out:
```
  bionic/libc/kernel/tools/generate_uapi_headers.sh --use-kernel-dir kernel_src/common
```
After above operations, will copy original kernel header files to `external/kernel-header` , I can see except a new folder for riscv `original/uapi/asm-riscv/`， other folders for other arch are not changed.

Next, run this command to copy the parsed files to bionic/libc/kernel/uapi:
```
  bionic/libc/kernel/tools/update_all.py
```

Please double check and let me know if we need update kernel uapi for aosp 12.

**Comment by MaoHan001** [comment]
The kernel verion of android 12 release are most android12-5.10-xxxx, we regenerate the kernel header with android12-5.10-xxxx kernel as they are under lts branch(5.12 is not a longterm kernel) and it might be better to keep kernel header with the same version of the linux kernel.

**Comment by unicornx** [comment]
> The kernel verion of android 12 release are most android12-5.10-xxxx, we regenerate the kernel header with android12-5.10-xxxx kernel as they are under lts branch(5.12 is not a longterm kernel) and it might be better to keep kernel header with the same version of the linux kernel.

OK. let's first keep it current status. 

BTW, do you know what's the strategy from Google, definitely they use 5.12 for their aosp 12 kernel uapi. A newer kernel header file (5.12) should be back compatible with 5.10, right?

**Comment by unicornx** [comment]
closed as per comment upon.

**Comment by unicornx** [comment]
latest status is we upgrade to use 5.12 kernel header files, with pr #14
